[package]
name = "am-example"
version = "0.1.0"
authors = []

[dependencies]
amethyst = {git = "https://github.com/amethyst/amethyst.git", branch = "master", features=["nightly"]}
line_drawing = "0.7.0"